import lvgl as lv
import lv_config
from lv_helper import SetFlag



ui_Screen1 = lv.obj()
ui_Screen1.remove_flag(lv.obj.FLAG.SCROLLABLE)
ui_Screen1.set_style_bg_color(lv.color_hex(0x000000), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Screen1.set_style_bg_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )

ui_Container5 = lv.obj(ui_Screen1)
ui_Container5.remove_style_all()
ui_Container5.set_width(lv.pct(90))
ui_Container5.set_height(lv.pct(90))
ui_Container5.set_align( lv.ALIGN.CENTER)
ui_Container5.set_flex_flow(lv.FLEX_FLOW.ROW_WRAP)
ui_Container5.set_flex_align(lv.FLEX_ALIGN.SPACE_EVENLY, lv.FLEX_ALIGN.START, lv.FLEX_ALIGN.SPACE_EVENLY)
SetFlag(ui_Container5, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container5, lv.obj.FLAG.SCROLLABLE, False)
ui_Container5.set_style_border_color(lv.color_hex(0x00D1FF), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container5.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container5.set_style_border_width( 5, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container5.set_style_pad_all( 5, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container5.set_style_pad_row( 5, lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container5.set_style_pad_column( 5, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container9 = lv.obj(ui_Container5)
ui_Container9.remove_style_all()
ui_Container9.set_height(lv.pct(30))
ui_Container9.set_style_flex_grow(1, 0)
SetFlag(ui_Container9, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container9, lv.obj.FLAG.SCROLLABLE, False)
ui_Container9.set_style_border_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container9.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container9.set_style_border_width( 2, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container10 = lv.obj(ui_Container5)
ui_Container10.remove_style_all()
ui_Container10.set_height(lv.pct(30))
ui_Container10.set_width(lv.pct(15))
SetFlag(ui_Container10, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container10, lv.obj.FLAG.SCROLLABLE, False)
ui_Container10.set_style_border_color(lv.color_hex(0xFF00FA), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container10.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container10.set_style_border_width( 1, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container11 = lv.obj(ui_Container5)
ui_Container11.remove_style_all()
ui_Container11.set_height(lv.pct(30))
ui_Container11.set_width(lv.pct(5))
SetFlag(ui_Container11, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container11, lv.obj.FLAG.SCROLLABLE, False)
ui_Container11.set_style_border_color(lv.color_hex(0xFF00FA), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container11.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container11.set_style_border_width( 1, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container12 = lv.obj(ui_Container5)
ui_Container12.remove_style_all()
ui_Container12.set_height(lv.pct(30))
ui_Container12.set_width(lv.pct(15))
SetFlag(ui_Container12, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container12, lv.obj.FLAG.SCROLLABLE, False)
ui_Container12.set_style_border_color(lv.color_hex(0xFF00FA), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container12.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container12.set_style_border_width( 1, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container13 = lv.obj(ui_Container5)
ui_Container13.remove_style_all()
ui_Container13.set_height(lv.pct(30))
ui_Container13.set_width(lv.pct(25))
SetFlag(ui_Container13, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container13, lv.obj.FLAG.SCROLLABLE, False)
ui_Container13.set_style_border_color(lv.color_hex(0xFF00FA), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container13.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container13.set_style_border_width( 1, lv.PART.MAIN | lv.STATE.DEFAULT )

# row 2
ui_Container14 = lv.obj(ui_Container5)
ui_Container14.remove_style_all()
ui_Container14.set_height(lv.pct(30))
ui_Container14.set_style_flex_grow(3, 0)
SetFlag(ui_Container14, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container14, lv.obj.FLAG.FLEX_IN_NEW_TRACK, True)# <--- important
SetFlag(ui_Container14, lv.obj.FLAG.SCROLLABLE, False)
ui_Container14.set_style_border_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container14.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container14.set_style_border_width( 2, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Label = lv.label(ui_Container14)
ui_Label.set_text('Yellow boxes have\nflex-grow enabled.')
ui_Label.center()

ui_Container15 = lv.obj(ui_Container5)
ui_Container15.remove_style_all()
ui_Container15.set_height(lv.pct(30))
ui_Container15.set_style_flex_grow(1, 0)
SetFlag(ui_Container15, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container15, lv.obj.FLAG.SCROLLABLE, False)
ui_Container15.set_style_border_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container15.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container15.set_style_border_width( 2, lv.PART.MAIN | lv.STATE.DEFAULT )

# row 3
ui_Container16 = lv.obj(ui_Container5)
ui_Container16.remove_style_all()
ui_Container16.set_height(lv.pct(30))
ui_Container16.set_width(lv.pct(28))
SetFlag(ui_Container16, lv.obj.FLAG.FLEX_IN_NEW_TRACK, True )# <--- important
SetFlag(ui_Container16, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container16, lv.obj.FLAG.SCROLLABLE, False)
ui_Container16.set_style_border_color(lv.color_hex(0xFF00FA), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container16.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container16.set_style_border_width( 1, lv.PART.MAIN | lv.STATE.DEFAULT )

ui_Container17 = lv.obj(ui_Container5)
ui_Container17.remove_style_all()
ui_Container17.set_height(lv.pct(30))
ui_Container17.set_style_flex_grow(1, 0)
SetFlag(ui_Container17, lv.obj.FLAG.CLICKABLE, False)
SetFlag(ui_Container17, lv.obj.FLAG.SCROLLABLE, False)
ui_Container17.set_style_border_color(lv.color_hex(0xFFFF00), lv.PART.MAIN | lv.STATE.DEFAULT )
ui_Container17.set_style_border_opa(255, lv.PART.MAIN| lv.STATE.DEFAULT )
ui_Container17.set_style_border_width( 2, lv.PART.MAIN | lv.STATE.DEFAULT )

lv.screen_load(ui_Screen1)

print(f'--- LVGL Version: {lv.version_major()}.{lv.version_minor()}. ---')